@Library('shared-library') _
pipeline {
    agent any

    parameters {
        string(name: 'VERSION', defaultValue: 'latest', description: 'Version to deploy')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }   
        stage('Set Version') {
            steps {
                script {
                    echo "Deploying version: ${params.VERSION}"
                }
            }
        }
        stage('Code Checkout') {
            steps {
                script{
                    clone("https://github.com/KrishnaPathak824/Jenkins-DevSecOps-Pipeline-AWS-EC2-EKS-Promethus-and-Grafana.git","main")
                }
            }
        }
        stage("Update: Kubernetes manifests"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/blog-app-frontend.*/blog-app-frontend:v${params.VERSION}/g deployment.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/blog-app-backend1.*/blog-app-backend1:v${params.VERSION}/g deployment.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/blog-app-backend2.*/blog-app-backend2:v${params.VERSION}/g deployment.yaml
                        """
                    }
                    
                }
            }
        }
        stage('Code Update and Commit') {
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh """
                    git remote set-url origin https://KrishnaPathak824:${GITHUB_TOKEN}@github.com/KrishnaPathak824/Jenkins-DevSecOps-Pipeline-AWS-EC2-EKS-Promethus-and-Grafana.git
                    git config user.email "jenkins@ci.local"
                    git config user.name "Jenkins CI"
                    git add deployment.yaml
                    git commit -m "Update Kubernetes manifests for version ${params.VERSION}[skip ci]" || echo "No changes to commit"
                    git push origin main
                    """
                }
            }
        }
    }
    post{
        always {
            cleanWs()
        }
        success {
            script {
                emailext attachLog: true,
                from: 'pathakkrishna824@gmail.com',
                subject: "Blog App has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'pathakkrishna824@gmail.com',
            mimeType: 'text/html'
            }
        }
        failure {
            script {
                emailext attachLog: true,
                from: 'pathakkrishna824@gmail.com',
                subject: "Blog App Build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'pathakkrishna824@gmail.com',
            mimeType: 'text/html'
            }
        }
    }
}